[package]
name = "rustblake"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
neon = ["blake3/neon"]

[dependencies]
blake3 = { version = "1.0.0", features = ["rayon"] }
time = "*"
chrono = "0.4"
